runtime: nodejs20

instance_class: F2

env_variables:
  NODE_ENV: production

handlers:
  - url: /
    static_files: index.html
    upload: index.html

  - url: /style\.css
    static_files: style.css
    upload: style.css

  - url: /script\.js
    static_files: script.js
    upload: script.js

  - url: /notes
    script: auto
    secure: always

# Enable automatic scaling
automatic_scaling:
  target_cpu_utilization: 0.6
  min_instances: 1
  max_instances: 5

# Health check configuration
health_check:
  enable_health_check: True
  check_interval_sec: 30
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2
  restart_threshold: 3
